# Imports and definitions

In [1]:
import numpy as np

In [47]:
def to_diag(S, m, n):
    "m x n matrix with (m) elements of S along diagonal, padded with zeros."
    res = np.zeros((m,n))
    for i, val in enumerate(S):
        res[i,i] = val
    return res

def dotall(Ms):
    "Multiply matrices [M1, M2, ..., Mn] together."
    res = np.identity(Ms[-1].shape[1])
    print(res)
    print(res.shape)
    for M in reversed(Ms):
        res = np.dot(M, res)
    return res



# Singular value decomposition

The singular value decomposition is an extremely general matrix factorization, which exists for any $m \times n$ complex matrix $M$.
We write $M = U_{m \times m} \Sigma_{m \times n} V^\dagger_{n \times n}$, where $U$ and $V$ are *unitary*, and $\Sigma$ has non-negative real numbers along the diagonal. The size of the matrices has been written out in the subscripts. The elements of $\Sigma$ (called singular values) are uniquely determined and the number of non-zero elements gives the *rank* of $M$. We can take these elements to be in descending order, say, which then makes $\Sigma$ uniquely determined by $M$.

Recall that the *rank* of a matrix is the dimension of the vector space spanned by its columns. The number of zero entries give the dimension of the *kernel*, or *null space*, i.e. the vector space that is mapped to 0 by $M$.

In [49]:
M = np.random.randn(9, 6) + 1j*np.random.randn(9, 6)
U, S, Vh = np.linalg.svd(M, full_matrices=True)
print(U.shape, S.shape, Vh.shape)
S = to_diag(S, 9, 6)
np.allclose(M, dotall([U, S, Vh]))

(9, 9) (6,) (6, 6)
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
(6, 6)


True

# Schmidt decomposition and entanglement